// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package alpinejs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HtmxDeferMutex() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_HtmxDeferMutex_fab0`,
		Function: `function __templ_HtmxDeferMutex_fab0(){document.addEventListener('htmx:beforeSwap', function (event) {
    Alpine.deferMutations()
  })
  document.addEventListener('htmx:afterSettle', function (event) {
    Alpine.flushAndStopDeferringMutations()
  })
}`,
		Call:       templ.SafeScript(`__templ_HtmxDeferMutex_fab0`),
		CallInline: templ.SafeScriptInline(`__templ_HtmxDeferMutex_fab0`),
	}
}

// trick tailwind since we derive this elsewhere
func translate() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"opacity-0 -translate-x-full scale-90\" x-transition:enter-end=\"opacity-100 translate-x-full scale-100\" x-transition:leave=\"transition ease-in duration-300\" x-transition:leave-start=\"opacity-100 translate-y-full scale-100\" x-transition:leave-end=\"opacity-0 -translate-y-full scale-90\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
